name: CI

on: [push]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install NPM packages
      run: npm install
    - name: Execute NPM tests
      run: npm test
      env:
        CI: true
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v1
    - name: Deploy on GitHub pages
      run: |
        npm install
        npm deploy
      env:
        CI: true
